---
kind: pipeline
name: default

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn test

  - name: Docker
    image: plugins/docker
    environment:
      BOT_CHANNEL:
        from_secret: BOT_CHANNEL
      TOKEN:
        from_secret: TOKEN
      BOT_GITHUB_TOKEN:
        from_secret: BOT_GITHUB_TOKEN
      REPO_OWNER: 'natel97'
      REPO_REPO: 'banter-bot'
    settings:
      repo: registry.nathaniallubitz.com/bots/banterbot
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      build_args_from_env:
        - TOKEN
        - BOT_CHANNEL
        - BOT_GITHUB_TOKEN
        - REPO_OWNER
        - REPO_REPO
    when:
      event:
        - push

  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: http://kube.nathaniallubitz.com
      kubernetes_user: drone
      namespace: default
      deployment: banter-bot
      container: banterbot
      repo: registry.nathaniallubitz.com/bots/banterbot
      tag: '${DRONE_COMMIT_SHA:0:8}'
      kubernetes_token:
        from_secret: kubernetes_token
      kubernetes_cert:
        from_secret: kubernetes_cert
    secrets: [kubernetes_token, kubernetes_cert]
    when:
      event:
        - push
trigger:
  branch:
    - main

---
kind: pipeline
name: deploy

steps:
  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: http://kube.nathaniallubitz.com
      kubernetes_user: drone
      namespace: default
      deployment: banter-bot
      container: banterbot
      repo: registry.nathaniallubitz.com/bots/banterbot
      tag: '${DRONE_COMMIT_SHA:0:8}'
      kubernetes_token:
        from_secret: kubernetes_token
      kubernetes_cert:
        from_secret: kubernetes_cert
    secrets: [kubernetes_token, kubernetes_cert]

trigger:
  target:
    - production
